# Generated by Django 3.2.15 on 2024-02-28 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, help_text='Дата заказа', verbose_name='Дата заказа'),
        ),
    ]
